2016/10/12 10:22:51 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in C:\Work\AppWeb\Yii\yii-1.1.14.f0fee9\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\Work\AppWeb\Yii\yii-1.1.14.f0fee9\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\Work\AppWeb\Yii\yii-1.1.14.f0fee9\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\Work\AppWeb\Yii\yii-1.1.14.f0fee9\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\Work\AppWeb\Yii\yii-1.1.14.f0fee9\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\Work\AppWeb\Yii\yii-1.1.14.f0fee9\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\Work\AppWeb\Yii\yii-1.1.14.f0fee9\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\Work\AppWeb\Yii\yii-1.1.14.f0fee9\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\Work\AppWeb\Yii\yii-1.1.14.f0fee9\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\Work\AppWeb\Yii\yii-1.1.14.f0fee9\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\Work\AppWeb\Yii\yii-1.1.14.f0fee9\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\Work\AppWeb\Yii\yii-1.1.14.f0fee9\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\Work\AppWeb\Yii\yii-1.1.14.f0fee9\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\Work\AppWeb\Yii\yii-1.1.14.f0fee9\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\Work\AppWeb\Yii\yii-1.1.14.f0fee9\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\Work\AppWeb\Yii\yii-1.1.14.f0fee9\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 c:\work\appweb\m_prueba1\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/mprueba1/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/mprueba1/index.php?r=gii/model/index
---
2016/10/12 10:33:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user".' in C:\Work\AppWeb\Yii\yii-1.1.14.f0fee9\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\Work\AppWeb\Yii\yii-1.1.14.f0fee9\framework\web\CWebApplication.php(141): CWebApplication->runController('user')
#1 C:\Work\AppWeb\Yii\yii-1.1.14.f0fee9\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 c:\work\appweb\m_prueba1\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/mprueba1/index.php?r=user
---
2016/10/12 10:33:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/create".' in C:\Work\AppWeb\Yii\yii-1.1.14.f0fee9\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\Work\AppWeb\Yii\yii-1.1.14.f0fee9\framework\web\CWebApplication.php(141): CWebApplication->runController('user/create')
#1 C:\Work\AppWeb\Yii\yii-1.1.14.f0fee9\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 c:\work\appweb\m_prueba1\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/mprueba1/index.php?r=user/create
---
